**KNN with Libraries**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df=pd.read_csv('KNNexcel.csv')
print(df)

    Height  Weight T shirt Size
0      158      58            M
1      158      59            M
2      158      63            M
3      160      59            M
4      160      60            M
5      163      60            M
6      163      61            M
7      160      64            L
8      163      64            L
9      165      61            L
10     165      62            L
11     165      65            L
12     168      62            L
13     168      63            L
14     168      66            L
15     170      63            L
16     170      64            L
17     170      68            L


Creating target variable and independent variable.

In [ ]:
x=df.iloc[:,:-1].values
print(x)
y=df.iloc[:,-1].values
print(y)

[[158  58]
 [158  59]
 [158  63]
 [160  59]
 [160  60]
 [163  60]
 [163  61]
 [160  64]
 [163  64]
 [165  61]
 [165  62]
 [165  65]
 [168  62]
 [168  63]
 [168  66]
 [170  63]
 [170  64]
 [170  68]]
['M' 'M' 'M' 'M' 'M' 'M' 'M' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L']


Splitting data into training and test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [24]:
print(x_train)

[[160  60]
 [158  63]
 [170  64]
 [170  68]
 [165  61]
 [160  64]
 [168  63]
 [165  65]
 [160  59]
 [158  58]
 [163  60]
 [170  63]
 [168  62]]


In [25]:
print(y_train)

['M' 'M' 'L' 'L' 'L' 'L' 'L' 'L' 'M' 'M' 'M' 'L' 'L']


In [26]:
print(x_test)

[[158  59]
 [163  61]
 [163  64]
 [165  62]
 [168  66]]


In [27]:
print(y_test)

['M' 'M' 'L' 'L' 'L']


Training the KNN model on training dataset.

In [29]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=4)
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=4)

Giving a new test instance of height=166, weight=63.

In [33]:
print(classifier.predict([[166,63]]))

['L']


Giving another test instance of height=156, weight=58

In [34]:
print(classifier.predict([[156,58]]))

['M']


Predicting class for test dataset.

In [35]:
y_pred=classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[['M' 'M']
 ['M' 'M']
 ['L' 'L']
 ['L' 'L']
 ['L' 'L']]


Making the confusion matrix

In [36]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[3 0]
 [0 2]]


1.0